/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as TableauDeBordRouteImport } from './routes/tableau-de-bord'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordRoute = TableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/restaurants': typeof RestaurantsRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/restaurants': typeof RestaurantsRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/restaurants': typeof RestaurantsRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connexion' | '/restaurants' | '/tableau-de-bord'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connexion' | '/restaurants' | '/tableau-de-bord'
  id: '__root__' | '/' | '/connexion' | '/restaurants' | '/tableau-de-bord'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnexionRoute: typeof ConnexionRoute
  RestaurantsRoute: typeof RestaurantsRoute
  TableauDeBordRoute: typeof TableauDeBordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord': {
      id: '/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof TableauDeBordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnexionRoute: ConnexionRoute,
  RestaurantsRoute: RestaurantsRoute,
  TableauDeBordRoute: TableauDeBordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
